context("init")
test_that("creates a default skeleton", {
  path <- tempdir()
  unlink(file.path(path, "*"), recursive = TRUE)
  expect_message(init_package("mypackage", path))
  expect_exists(file.path(path, ".git"))
  expect_exists(file.path(path, "tests"))
  expect_exists(file.path(path, "DESCRIPTION"))
  expect_exists(file.path(path, "README.Rmd"))
  expect_exists(file.path(path, "CONDUCT.md"))
  expect_exists(file.path(path, ".travis.yml"))
  expect_exists(file.path(path, "appveyor.yml"))
  expect_exists(file.path(path, ".lintr"))
  expect_exists(file.path(path, ".gitignore"))
  expect_exists(file.path(path, ".Rbuildignore"))
  expect_exists(file.path(path, "NAMESPACE"))
  expect_exists(file.path(path, "NEWS.md"))
})

test_that("check if name is already taken on CRAN", {
  path <- tempdir()
  unlink(file.path(path, "*"), recursive = TRUE)
  expect_error(init_package("Rcpp", path))
  expect_message(init_package("Rcpp", path, check_cran_name = FALSE))
})
